ALTER TABLE `result` CHANGE COLUMN `handicap` `handicap_home` tinyint NOT NULL;
ALTER TABLE `result` CHANGE COLUMN `over_under` `over_under_home` tinyint NOT NULL;
ALTER TABLE `result` CHANGE COLUMN `single` `single_home` tinyint NOT NULL;
ALTER TABLE `result` ADD COLUMN `handicap_away` tinyint NOT NULL AFTER `handicap_home`;
ALTER TABLE `result` ADD COLUMN `over_under_away` tinyint NOT NULL AFTER `over_under_home`;
ALTER TABLE `result` ADD COLUMN `single_away` tinyint NOT NULL AFTER `single_home`;
ALTER TABLE `result` ADD COLUMN `single_tie` tinyint NOT NULL AFTER `single_away`;
ALTER TABLE `result` ADD COLUMN `single_odds` decimal(3,2) NOT NULL AFTER `over_under_bet`;
ALTER TABLE `prediction` CHANGE COLUMN `handicap` `handicap_home` tinyint NOT NULL;
ALTER TABLE `prediction` CHANGE COLUMN `over_under` `over_under_home` tinyint NOT NULL;
ALTER TABLE `prediction` CHANGE COLUMN `single` `single_home` tinyint NOT NULL;
ALTER TABLE `prediction` ADD COLUMN `handicap_away` tinyint NOT NULL AFTER `handicap_home`;
ALTER TABLE `prediction` ADD COLUMN `over_under_away` tinyint NOT NULL AFTER `over_under_home`;
ALTER TABLE `prediction` ADD COLUMN `single_away` tinyint NOT NULL AFTER `single_home`;
ALTER TABLE `prediction` ADD COLUMN `single_tie` tinyint NOT NULL AFTER `single_away`;
ALTER TABLE `event` CHANGE COLUMN `handicap_home` `handicap_home_bet` decimal(3,2) NOT NULL;
ALTER TABLE `event` CHANGE COLUMN `handicap_away` `handicap_away_bet` decimal(3,2) NOT NULL;
ALTER TABLE `event` CHANGE COLUMN `over_under_home` `over_under_home_bet` decimal(3,2) NOT NULL;
ALTER TABLE `event` CHANGE COLUMN `over_under_away` `over_under_away_bet` decimal(3,2) NOT NULL;
ALTER TABLE `event` ADD COLUMN `home_team_upload_id` bigint NOT NULL AFTER `home_team_id`;
ALTER TABLE `event` ADD COLUMN `away_team_upload_id` bigint NOT NULL AFTER `away_team_id`;