ALTER TABLE `accounting` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `accounting` ADD INDEX `from_id` (`from_id`);
ALTER TABLE `accounting` ADD INDEX `to_id` (`to_id`);
ALTER TABLE `accounting` ADD INDEX `reference_id` (`reference_id`);
ALTER TABLE `accounting` ADD INDEX `credit_id` (`credit_id`);
ALTER TABLE `adjustment` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `adjustment` ADD INDEX `points` (`points`);
ALTER TABLE `adjustment` ADD INDEX `points_before` (`points_before`);
ALTER TABLE `adjustment` ADD INDEX `points_after` (`points_after`);
ALTER TABLE `adjustment` ADD INDEX `voucher` (`voucher`);
ALTER TABLE `adjustment` ADD INDEX `voucher_before` (`voucher_before`);
ALTER TABLE `adjustment` ADD INDEX `voucher_after` (`voucher_after`);
ALTER TABLE `ads_button` ADD INDEX `image_upload_id` (`image_upload_id`);
ALTER TABLE `article` ADD INDEX `title` (`title`);
ALTER TABLE `article` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `article` ADD INDEX `sub_category_id` (`sub_category_id`);
ALTER TABLE `article` ADD INDEX `chatroom_id` (`chatroom_id`);
ALTER TABLE `article` ADD INDEX `upload_id` (`upload_id`);
ALTER TABLE `article` ADD INDEX `type` (`type`);
ALTER TABLE `article` ADD INDEX `active_at` (`active_at`);
ALTER TABLE `balance` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `balance` ADD INDEX `credit_id` (`credit_id`);
ALTER TABLE `balance` ADD INDEX `date` (`date`);
ALTER TABLE `category` ADD INDEX `type` (`type`);
ALTER TABLE `category` ADD INDEX `parent_id` (`parent_id`);
ALTER TABLE `category` ADD INDEX `upload_id` (`upload_id`);
ALTER TABLE `category` ADD INDEX `sorting` (`sorting`);
ALTER TABLE `category` ADD INDEX `article_count` (`article_count`);
ALTER TABLE `event` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `event` ADD INDEX `league_id` (`league_id`);
ALTER TABLE `event` ADD INDEX `match_at` (`match_at`);
ALTER TABLE `event` ADD INDEX `prediction_end_at` (`prediction_end_at`);
ALTER TABLE `gift` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `gift` ADD INDEX `sub_category_id` (`sub_category_id`);
ALTER TABLE `gift` ADD INDEX `start_at` (`start_at`);
ALTER TABLE `gift` ADD INDEX `end_at` (`end_at`);
ALTER TABLE `gift_redeem` ADD INDEX `gift_id` (`gift_id`);
ALTER TABLE `gift_redeem` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `gift_redeem` ADD INDEX `status` (`status`);
ALTER TABLE `league` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `team` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `season_matches` ADD INDEX `match_id` (`match_id`);
ALTER TABLE `season_list` ADD INDEX `category_season` (`category_id`, `season_id`);
ALTER TABLE `season_list` ADD INDEX `league_id` (`league_id`);
ALTER TABLE `season_player_stats_basketball` ADD INDEX `season_player` (`season_id`, `player_id`);
ALTER TABLE `season_player_stats_soccer` ADD INDEX `season_player` (`season_id`, `player_id`);
ALTER TABLE `season_ranking_basketball` ADD INDEX `season_team` (`season_id`, `team_id`);
ALTER TABLE `season_ranking_soccer` ADD INDEX `season_team` (`season_id`, `team_id`);
ALTER TABLE `season_matches` ADD INDEX `season_id` (`season_id`);
ALTER TABLE `team` ADD INDEX `league_id` (`league_id`);
ALTER TABLE `league` DROP INDEX `category_id`, ADD INDEX `category_id` (`category_id`, `api_id`) USING BTREE;
ALTER TABLE `message` ADD INDEX `user_message` (`chatroom_id`, `parent_id`, `status`);
ALTER TABLE `message_like` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `prediction` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `prediction` ADD INDEX `event_id` (`event_id`);
ALTER TABLE `prediction_stats` ADD INDEX `user_stats` (`user_id`, `league_id`);
ALTER TABLE `prediction_rate` ADD INDEX `user_prediction_rate` (`user_id`, `league_id`);
ALTER TABLE `prediction_top_ten` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `prediction_top_ten` ADD INDEX `event_id` (`event_id`);
ALTER TABLE `prediction_top_ten_unlock` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `prediction_top_ten_unlock` ADD INDEX `event_id` (`event_id`);
ALTER TABLE `promotion` ADD INDEX `active_promo` (`start_at`, `end_at`);
ALTER TABLE `promotion_redeem` ADD INDEX `promotion_id` (`promotion_id`);
ALTER TABLE `promotion_redeem` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `promotion_redeem` ADD INDEX `status` (`status`);
ALTER TABLE `result` ADD INDEX `event_id` (`event_id`);
ALTER TABLE `top_ten` ADD INDEX `user_id` (`user_id`);
ALTER TABLE `top_ten` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `top_ten` ADD INDEX `league_id` (`league_id`);
ALTER TABLE `top_ten` ADD INDEX `month` (`month`);
ALTER TABLE `top_ten` ADD INDEX `year` (`year`);
ALTER TABLE `top_ten_rate` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `upload` ADD INDEX `category_id` (`category_id`);
ALTER TABLE `upload` ADD INDEX `url` (`url`);